CREATE TABLE IF NOT EXISTS cards(
    card_id INT NOT NULL AUTO_INCREMENT,
    card_number INT NOT NULL,
    owner VARCHAR(50) NOT NULL,
    expired DATE NOT NULL,
    security_code INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(card_id)
);